services:
  - type: web
    name: telegram-whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NPM_VERSION 
        value: "9.6.7"
      - key: PORT
        value: "10000"
